fullnameOverride: postgres

annotations:
  sidecar.istio.io/inject: "false"

image:
  repository: registry.hub.docker.com/library
  name: postgres
  tag: 9.6.10
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5432

service:
  ports:
    - name: postgres
      port: 5432
