fullnameOverride: postgres

image:
  repository: registry.hub.docker.com/library
  name: postgres
  tag: 10
  pullPolicy: IfNotPresent

ports:
  - containerPort: 5432

service:
  ports:
    - port: 5432